# Generated by Django 5.0.2 on 2024-02-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='count',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='test', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
