# Generated by Django 5.0.2 on 2024-02-23 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_rating_count_product_image_rating_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/images/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.rating'),
        ),
    ]
